<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INHL1290" failures="1" tests="3" name="org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API" time="7.084" errors="0" timestamp="2022-12-22T13:12:29 IST" skipped="0">
  <testcase classname="org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API" name="GetSingleBusinessInvitationDetails_RegisteredBusinessID" time="3.559">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API.GetSingleBusinessInvitationDetails_RegisteredBusinessID(Get_Single_BusinessInviationDetails_Test_API.java:25)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- GetSingleBusinessInvitationDetails_RegisteredBusinessID -->
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API" name="GetSingleBusinessInvitationDetails_InvaildBusinessID" time="1.614"/>
  <system-out/>
  <testcase classname="org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API" name="GetSingleBusinessInvitationDetails_InvitedBusinessID" time="1.911"/>
  <system-out/>
</testsuite> <!-- org.pineapple.testscripts.Get_Single_BusinessInviationDetails_Test_API -->
